version: 2.1

# Define the jobs we want to run for this project
jobs:
  connect:
    docker:
      - image: "circleci/sshd:0.1"
    steps:
      - checkout
      - run: touch key.pem && echo $KEY > key.pem && chmod 400 key.pem && ssh -i key.pem -o "StrictHostKeyChecking no" ubuntu@34.215.212.181 "cat /var/log/nginx/access.log"

# Orchestrate our job run sequence
workflows:
  connect:
    jobs:
      - connect
