version: 2.1

# Define the jobs we want to run for this project
jobs:
  connect:
    docker:
      - image: "circleci/sshd:0.1"
    steps:
      - checkout
      - run: touch key.pem && echo $KEY 

# Orchestrate our job run sequence
workflows:
  connect:
    jobs:
      - connect
